# languageCode = "en-us"

baseurl = "https://www.vangorden.dev"
title = "Noah Van Gorden"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true

[blackfriday]
    hrefTargetBlank = true

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Noah Van Gorden"
    info = "Aspiring Software Engineer"
    description = "Noah Van Gorden's personal website"
    keywords = "blog,developer,engineer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    # footercontent = "Enter a footer text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/vangorden/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/vangorden/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 2
    url = "https://linkedin.com/in/noahvangorden"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 1
    url  = "/contact/"
